import json
import os
import glob
import re

print("Starting ultimate polish script...")

# 1. Update translations.json
translations_file = r"d:\BPIS_2026\frontend\dashboard\src\translations.json"
with open(translations_file, "r", encoding="utf-8") as f:
    t_data = json.load(f)

en = t_data["en"]
hi = t_data["hi"]

en.update({
    "runSimulationBtn": "Run Simulation",
    "districtsBelow70": "districts have literacy rate below 70%",
    "highestRiskDistLabel": "Highest risk district:",
    "avgLiteracyRateLabel": "Average literacy rate:",
    "generatedByBPIS": "Generated by BPIS Intelligence Engine",
    "focusInfrastructure": "Focus infrastructure funding towards localized skill-development to leverage the highly literate demographic.",
    "prioritizeSarvaShiksha": "Prioritize 'Sarva Shiksha' funding and aggressive adult literacy camps immediately.",
    "districtNameMap": {
        "thane": "Thane", "mumbai suburban": "Mumbai Suburban", "barddhaman": "Barddhaman", 
        "jaipur": "Jaipur", "murshidabad": "Murshidabad", "purba champaran": "Purba Champaran", 
        "patna": "Patna", "allahabad": "Allahabad", "bangalore": "Bangalore", "pune": "Pune",
        "kupwara": "Kupwara", "badgam": "Badgam", "leh(ladakh)": "Leh(Ladakh)", "kargil": "Kargil",
        "punch": "Punch", "rajouri": "Rajouri", "kathua": "Kathua", "baramula": "Baramula",
        "bandipore": "Bandipore", "srinagar": "Srinagar", "north twenty four parganas": "North 24 Parganas",
        "south twenty four parganas": "South 24 Parganas"
    }
})

hi.update({
    "runSimulationBtn": "सिमुलेशन चलाएँ",
    "districtsBelow70": "जिलों की साक्षरता दर 70% से कम है",
    "highestRiskDistLabel": "उच्चतम जोखिम वाला जिला:",
    "avgLiteracyRateLabel": "औसत साक्षरता दर:",
    "generatedByBPIS": "BPIS इंटेलिजेंस इंजन द्वारा उत्पन्न",
    "focusInfrastructure": "अत्यधिक साक्षर जनसांख्यिकी का लाभ उठाने के लिए स्थानीयकृत कौशल-विकास की दिशा में बुनियादी ढांचे के वित्तपोषण पर ध्यान दें।",
    "prioritizeSarvaShiksha": "तुरंत 'सर्व शिक्षा' वित्तपोषण और आक्रामक वयस्क साक्षरता शिविरों को प्राथमिकता दें।",
    "districtNameMap": {
        "thane": "ठाणे", "mumbai suburban": "मुंबई उपनगरीय", "barddhaman": "बर्धमान", 
        "jaipur": "जयपुर", "murshidabad": "मुर्शिदाबाद", "purba champaran": "पूर्वी चंपारण", 
        "patna": "पटना", "allahabad": "इलाहाबाद", "bangalore": "बैंगलोर", "pune": "पुणे",
        "kupwara": "कुपवाड़ा", "badgam": "बडगाम", "leh(ladakh)": "लेह(लद्दाख)", "kargil": "कारगिल",
        "punch": "पुंछ", "rajouri": "राजौरी", "kathua": "कठुआ", "baramula": "बारामूला",
        "bandipore": "बांदीपोरा", "srinagar": "श्रीनगर", "north twenty four parganas": "उत्तर 24 परगना",
        "south twenty four parganas": "दक्षिण 24 परगना"
    }
})

with open(translations_file, "w", encoding="utf-8") as f:
    json.dump(t_data, f, indent=2, ensure_ascii=False)


# 2. Patch AIPolicyAdvisor.js
av_file = r"d:\BPIS_2026\frontend\dashboard\src\components\AIPolicyAdvisor.js"
with open(av_file, "r", encoding="utf-8") as f:
    av = f.read()

av = av.replace(">Run Simulation</button>", ">{t('runSimulationBtn')}</button>")
av = av.replace(">\n        Run Simulation\n      </button>", ">\n        {t('runSimulationBtn')}\n      </button>")

get_district_func = """<XAxis dataKey="district" tickFormatter={(val) => { const nameMap = t('districtNameMap'); const mapped = (nameMap && nameMap[val.toLowerCase()]) ? nameMap[val.toLowerCase()] : val; return mapped.charAt(0).toUpperCase() + mapped.slice(1); }} />"""
av = av.replace("<XAxis dataKey=\"district\" />", get_district_func)

with open(av_file, "w", encoding="utf-8") as f:
    f.write(av)

# 3. Patch DistrictCompare.js
dc_file = r"d:\BPIS_2026\frontend\dashboard\src\components\DistrictCompare.js"
with open(dc_file, "r", encoding="utf-8") as f:
    dc = f.read()

helper = """
  // Helper to safely format district name explicitly
  const getDistrictName = (name) => {
    if (!name) return "";
    const nameMap = t('districtNameMap');
    if (nameMap && nameMap[name.toLowerCase()]) {
      return nameMap[name.toLowerCase()];
    }
    return name.charAt(0).toUpperCase() + name.slice(1);
  };
"""
dc = dc.replace("const selectedData = getDistrictData(selectedDistrictName);", "const selectedData = getDistrictData(selectedDistrictName);" + helper)

dc = dc.replace("<Bar dataKey={selectedDistrictName}", "<Bar name={getDistrictName(selectedDistrictName)} dataKey={selectedDistrictName}")
dc = dc.replace("<Radar name={selectedDistrictName}", "<Radar name={getDistrictName(selectedDistrictName)}")

dc = dc.replace("Generated by BPIS Intelligence Engine", "{t('generatedByBPIS')}")
dc = dc.replace("Focus infrastructure funding towards localized skill-development to leverage the highly literate demographic.", "{t('focusInfrastructure')}")
dc = dc.replace("Prioritize 'Sarva Shiksha' funding and aggressive adult literacy camps immediately.", "{t('prioritizeSarvaShiksha')}")

dc = dc.replace("selectedData.district,", "getDistrictName(selectedData.district),")

pdf_switch = """      didParseCell: function(data) {
        if (data.section === 'body' && data.column.index === 0) {
          if (/[a-zA-Z]/.test(data.cell.raw)) {
             data.cell.styles.font = 'helvetica';
          }
        }
      },"""
dc = dc.replace("""      didParseCell: function(data) {
        if (data.section === 'body' && data.column.index === 0) {
          data.cell.styles.font = 'helvetica';
        }
      },""", pdf_switch)

dc = dc.replace("""    doc.text(selectedDistrictName.charAt(0).toUpperCase() + selectedDistrictName.slice(1), 20 + titleWidth, 52);""", """    const pDName = getDistrictName(selectedDistrictName);
    if (/[a-zA-Z]/.test(pDName)) {
        doc.setFont('helvetica', 'bold');
    }
    doc.text(pDName, 20 + titleWidth, 52);""")

with open(dc_file, "w", encoding="utf-8") as f:
    f.write(dc)


# 4. Patch Insights.js
ins_file = r"d:\BPIS_2026\frontend\dashboard\src\components\Insights.js"
with open(ins_file, "r", encoding="utf-8") as f:
    ins = f.read()

ins = ins.replace("import { useEffect, useState } from \"react\";", "import { useEffect, useState } from \"react\";\nimport { useLanguage } from '../contexts/LanguageContext';")
ins = ins.replace("function Insights() {", "function Insights() {\n  const { t } = useLanguage();")
ins = ins.replace("{stats.lowLiteracy} districts have literacy rate below 70%", "{stats.lowLiteracy} {t('districtsBelow70')}")
ins = ins.replace("Highest risk district: <b>{stats.highRisk}</b>", "{t('highestRiskDistLabel')} <b style={{textTransform: 'capitalize'}}>{(t('districtNameMap') && t('districtNameMap')[stats.highRisk?.toLowerCase()]) || stats.highRisk}</b>")
ins = ins.replace("Average literacy rate: {stats.avgLiteracy}%", "{t('avgLiteracyRateLabel')} {stats.avgLiteracy}%")

with open(ins_file, "w", encoding="utf-8") as f:
    f.write(ins)


# 5. Patch external chart files
files_to_patch = [
    r"d:\BPIS_2026\frontend\dashboard\src\components\Charts.js", 
    r"d:\BPIS_2026\frontend\dashboard\src\components\PopulationChart.js",
    r"d:\BPIS_2026\frontend\dashboard\src\components\DistrictTable.js",
    r"d:\BPIS_2026\frontend\dashboard\src\components\PriorityTable.js"
]

tick_formatter = """<XAxis dataKey="district" tickFormatter={(val) => { const nameMap = t('districtNameMap'); const mapped = (nameMap && nameMap[val?.toLowerCase()]) ? nameMap[val.toLowerCase()] : val; return mapped?.charAt(0).toUpperCase() + mapped?.slice(1); }} />"""

for target in files_to_patch:
    if os.path.exists(target):
        with open(target, "r", encoding="utf-8") as f:
            t_content = f.read()
            
        if "useLanguage" not in t_content:
            t_content = t_content.replace('import React', 'import React;\nimport { useLanguage } from "../contexts/LanguageContext";', 1)
            t_content = re.sub(r'const [A-Za-z]+ = \(\) => {', lambda m: m.group(0) + '\n  const { t } = useLanguage();\n', t_content)
            
        t_content = t_content.replace('<XAxis dataKey="district" />', tick_formatter)
        t_content = t_content.replace('<td>{item.district}</td>', '<td style={{textTransform: "capitalize"}}>{(t("districtNameMap") && t("districtNameMap")[item.district?.toLowerCase()]) || item.district}</td>')
        
        with open(target, "w", encoding="utf-8") as f:
            f.write(t_content)


print("Ultimate Polish Done!")
