import os

file_path = r"d:\BPIS_2026\frontend\dashboard\src\components\DistrictCompare.js"
with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

# 1. Imports
content = content.replace(
    "import autoTable from 'jspdf-autotable';",
    "import autoTable from 'jspdf-autotable';\nimport { useLanguage } from '../contexts/LanguageContext';\nimport { notoSansDevanagariBase64 } from '../assets/fontBase64';"
)

# 2. Add hook
content = content.replace(
    "const [selectedDistrictName, setSelectedDistrictName] = useState('');",
    "const [selectedDistrictName, setSelectedDistrictName] = useState('');\n  const { t, language } = useLanguage();"
)

# 3. Chart data
content = content.replace(
    "const barData = selectedDistrictName ? [\n    { name: 'Literacy Rate (%)', [selectedDistrictName]: currentLiteracy, 'National Average': nationalLiteracy }\n  ] : [];",
    "const barData = selectedDistrictName ? [\n    { name: t('literacyRate'), [selectedDistrictName]: currentLiteracy, [t('nationalAverage')]: nationalLiteracy }\n  ] : [];"
)

content = content.replace(
    "const radarData = selectedDistrictName ? [\n    { subject: 'Literacy', A: currentLiteracy, B: nationalLiteracy, fullMark: 100 },\n    { subject: 'Density', A: currentDensity/4, B: nationalDensity/4, fullMark: 100 },\n    { subject: 'Gender Ratio', A: currentGenderRatio/10, B: nationalGenderRatio/10, fullMark: 100 }\n  ] : [];",
    "const radarData = selectedDistrictName ? [\n    { subject: t('literacyRate'), A: currentLiteracy, B: nationalLiteracy, fullMark: 100 },\n    { subject: t('density'), A: currentDensity/4, B: nationalDensity/4, fullMark: 100 },\n    { subject: t('genderRatio'), A: currentGenderRatio/10, B: nationalGenderRatio/10, fullMark: 100 }\n  ] : [];"
)

# 4. JSX text strings (Chart rendering)
content = content.replace(
    "Bar dataKey=\"National Average\" fill=\"#1e293b\"",
    "Bar dataKey={t('nationalAverage')} fill=\"#1e293b\""
)
content = content.replace(">District Comparison Deep Dive<", ">{t('districtCompareTitle')}<")
content = content.replace("> Export PDF<", "> {t('exportPDF')}<")
content = content.replace(">{selectedDistrictName} vs National Setup<", ">{selectedDistrictName} {t('vsNationalSetup')}<")
content = content.replace(">Socio-Economic Radar<", ">{t('socioEconomicRadar')}<")
content = content.replace(">AI Policy Insight<", ">{t('aiPolicyInsight')}<")
content = content.replace("> Generated by BPIS Intelligence Engine<", "> {t('generatedBy')}<")
content = content.replace(">No District Selected<", ">{t('noDistrictSelected')}<")
content = content.replace(">Please select a district from the search field above to view Deep Dive Charts, Reports, and Insights.<", ">{t('pleaseSelectDistrict')}<")

content = content.replace("<strong>Policy Gap Identified:</strong>", "<strong>{t('policyGapIdentified')}</strong>")
content = content.replace("<strong>Recommendation:</strong>", "<strong>{t('recommendation')}</strong>")

# 5. PDF Function
# We will do a regex or string replacement for the handleDownloadReport
old_pdf_code = """  // --- PDF REPORT GENERATOR ---
  const handleDownloadReport = () => {
    if (!selectedData) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;

    // Gov Letterhead Outline
    doc.setDrawColor(15, 23, 42); 
    doc.setLineWidth(1);
    doc.rect(10, 10, pageWidth - 20, pageHeight - 20);

    // Official Title Header
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("BHARAT POLICY INTELLIGENCE SYSTEM - OFFICIAL REPORT", pageWidth / 2, 25, { align: "center" });

    // Auto-Timestamp
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, pageWidth / 2, 32, { align: "center" });

    // Section Bar
    doc.setDrawColor(203, 213, 225); // slate-300
    doc.line(20, 40, pageWidth - 20, 40);

    // District Table
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(234, 88, 12); // BPIS Orange
    doc.text(`District Intelligence Profile: ${selectedDistrictName}`, 20, 52);

    autoTable(doc, {
      startY: 56,
      head: [['District Name', 'Total Population', 'Literacy Rate (%)']],
      body: [
        [
          selectedData.district, 
          selectedData.population?.toLocaleString() || 'N/A', 
          selectedData.literacy_rate?.toFixed(2) || 'N/A'
        ]
      ],
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42], textColor: 255 },
      styles: { font: 'helvetica', fontSize: 11, cellPadding: 6 },
      margin: { left: 20, right: 20 }
    });

    // AI Policy Recommendation Section
    const nextY = doc.lastAutoTable.finalY + 15 || 95;
    
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(234, 88, 12);
    doc.text("Strategic Policy Advice", 20, nextY);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(15, 23, 42);
    
    // Dynamic bullet math
    const gapLiteral = Math.abs(gap).toFixed(1);
    const popText = selectedData.population ? (selectedData.population / 1000000).toFixed(1) + "M" : "the regional";
    
    const bullet1 = gap > 0 
      ? `• Targeting a critical ${gapLiteral}% Literacy Gap via prioritized 'Samagra Shiksha' funding.` 
      : `• Sustaining a positive literacy surplus (${gapLiteral}% above avg) via advanced skill hubs.`;
    const bullet2 = `• Infrastructure expansion modeled to support the ${popText} localized population density.`;
    const bullet3 = `• Deploying early-warning monitoring to bridge identified socio-economic disparities.`;

    doc.text(bullet1, 20, nextY + 10);
    doc.text(bullet2, 20, nextY + 18);
    doc.text(bullet3, 20, nextY + 26);

    // Official Footer Mark
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text("Confidential - For Internal Govt Use Only", pageWidth / 2, pageHeight - 15, { align: "center" });

    // Auto-Download trigger
    doc.save(`BPIS_Report_${selectedDistrictName.replace(/\s+/g, '_')}.pdf`);
  };"""

new_pdf_code = """  // --- PDF REPORT GENERATOR ---
  const handleDownloadReport = () => {
    if (!selectedData) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;

    if (language === 'hi') {
      doc.addFileToVFS('NotoSansDevanagari-Regular.ttf', notoSansDevanagariBase64);
      doc.addFont('NotoSansDevanagari-Regular.ttf', 'NotoSansDevanagari', 'normal');
      doc.setFont('NotoSansDevanagari');
    }

    // Gov Letterhead Outline
    doc.setDrawColor(15, 23, 42); 
    doc.setLineWidth(1);
    doc.rect(10, 10, pageWidth - 20, pageHeight - 20);

    const setFontSafe = (weight) => {
        if (language === 'hi') {
            doc.setFont('NotoSansDevanagari', 'normal');
        } else {
            doc.setFont('helvetica', weight);
        }
    };

    // Official Title Header
    doc.setTextColor(15, 23, 42);
    setFontSafe('bold');
    doc.setFontSize(16);
    doc.text(t("reportHeader"), pageWidth / 2, 25, { align: "center" });

    // Auto-Timestamp
    setFontSafe('normal');
    doc.setFontSize(10);
    doc.text(`${t("generatedOn")}: ${new Date().toLocaleString()}`, pageWidth / 2, 32, { align: "center" });

    // Section Bar
    doc.setDrawColor(203, 213, 225); // slate-300
    doc.line(20, 40, pageWidth - 20, 40);

    // District Table
    doc.setFontSize(14);
    setFontSafe('bold');
    doc.setTextColor(234, 88, 12); // BPIS Orange
    doc.text(`${t("districtProfile")}: ${selectedDistrictName}`, 20, 52);

    autoTable(doc, {
      startY: 56,
      head: [[t("districtName"), t("totalPopulation"), t("literacyRate")]],
      body: [
        [
          selectedData.district, 
          selectedData.population?.toLocaleString() || 'N/A', 
          selectedData.literacy_rate?.toFixed(2) || 'N/A'
        ]
      ],
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42], textColor: 255 },
      styles: { 
          font: language === 'hi' ? 'NotoSansDevanagari' : 'helvetica', 
          fontSize: 11, 
          cellPadding: 6 
      },
      margin: { left: 20, right: 20 }
    });

    // AI Policy Recommendation Section
    const nextY = doc.lastAutoTable.finalY + 15 || 95;
    
    doc.setFontSize(14);
    setFontSafe('bold');
    doc.setTextColor(234, 88, 12);
    doc.text(t("strategicAdvice"), 20, nextY);

    doc.setFontSize(11);
    setFontSafe('normal');
    doc.setTextColor(15, 23, 42);
    
    // Dynamic bullet math
    const gapLiteral = Math.abs(gap).toFixed(1);
    const popText = selectedData.population ? (selectedData.population / 1000000).toFixed(1) + "M" : "the regional";
    
    const bullet1 = gap > 0 
      ? t("bullet1Gap").replace("{{gap}}", gapLiteral) 
      : t("bullet1Surplus").replace("{{gap}}", gapLiteral);
    const bullet2 = t("bullet2").replace("{{pop}}", popText);
    const bullet3 = t("bullet3");

    doc.text(bullet1, 20, nextY + 10);
    doc.text(bullet2, 20, nextY + 18);
    doc.text(bullet3, 20, nextY + 26);

    // Official Footer Mark
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(t("confidentialFooter"), pageWidth / 2, pageHeight - 15, { align: "center" });

    // Auto-Download trigger
    doc.save(`BPIS_Report_${selectedDistrictName.replace(/\s+/g, '_')}.pdf`);
  };"""

content = content.replace(old_pdf_code, new_pdf_code)

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Updated DistrictCompare.js successfully!")
